### ISSUE TITLE
Does ESP32 WiFi interfere with SX1280?

### ISSUE THREAD

**Issue by ONLYstcm** [LoRaTracker/SX12XX-LoRa#12]
Not really an issue but just a question. I'm curious to know if the WiFi communication between the ESP32 effects LoRa SX1280 because the share the same bandwidth. I understand the SX1280 has good WiFi and bluetooth immunity but I wonder if this applies when both these modules are functioning in close proximity on one breadboard/pcb etc

**Comment by LoRaTracker** [comment]
I have not carried out any tests for that, so cannot say.
